#! /usr/local/bin/bash

source `dirname ${0}`/Krnl.include

cp ${VELCONFSRCDIR}/* ${HEAD}/sys/amd64/conf/./ && \
( ( cd ${HEAD}/sys/amd64/conf && config -d ${KERNBUILDDIR} $KERN_CONFIG ) && \
  ((cd ${VELPATHTOBSDSRCS}/sys && make -j${VELNUMCPUS}  -m ${VELMK} clean \
     cleandepend depend) && \
  (cd ${VELPATHTOBSDSRCS} && make -j24 buildkernel )) \
     > ${BLDERROUT} 2>&1 || (less '+/error: ' ${BLDERROUT} 2>&1; \
         exit 1) && tail -n 20 $BLDERROUT )

